services:
  - type: web
    name: heart-disease-prediction
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
