services:
  - type: web
    name: heart-disease-prediction
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
